#! /usr/bin/env python3
"""Barrier free web service."""

from immobrowse import CONFIG
from barrierfree import APPLICATION


if __name__ == '__main__':
    HOST = CONFIG['barrierfree']['host']
    PORT = int(CONFIG['barrierfree']['port'])
    APPLICATION.run(host=HOST, port=PORT)
