#! /usr/bin/env python3
"""Immobrowse web service."""

from immobrowse import CONFIG, APPLICATION


if __name__ == '__main__':
    HOST = CONFIG['wsgi']['host']
    PORT = int(CONFIG['wsgi']['port'])
    APPLICATION.run(host=HOST, port=PORT)
