DROP TABLE IF EXISTS `#__immobrowse`;

CREATE TABLE `#__immobrowse` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `customer` VARCHAR(16) NOT NULL,
   PRIMARY KEY  (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;
